### PR TITLE
433 MHz testing additions

### PR DESCRIPTION
**Pull request by adamfowleruk**
As promised! Updates for 433MHz operation.
Files and readme changes
Added:-
 - XML and header files for 433 MHz in fixed and variable length operation
 - Support for a FREQ_433 define to use 433MHz mode
 - .gitignore added
 - README updated to reflect additional 433MHz testing, using 433MHz operation, and the SDI/MISO SDO/MOSI reversal issue on the Arduino Pro Mini

### CODE REVIEW

**Comment by GIPdA** [comment]
Thanks, just a thing before I merge it, about the MISO/MOSI reversal: are you sure you're using the correct pinout? I checked on the internet, and MISO is pin 12, MOSI is pin 11, as it should be. Which is the opposite of yours, and explains your issue with the SPI.

http://www.dominicdube.com/wp-content/uploads/ProMiniPinout.png

**Comment by adamfowleruk** [comment]
In my circuit Zeta SDO goes to Pro Mini MOSI and Zeta SDI goes to Pro Mini MISO. I used the same diagram you shared, and the Zeta PDF download datasheet.

**Comment by GIPdA** [comment]
Something's wrong... Is it a genuine pro mini?

Here is my wiring with a pro mini (not genuine but same pinout):
zeta promini
SDO to MISO (12), SDI to MOSI (11)...

**Comment by adamfowleruk** [comment]
Mine is wired up the same as yours (now!), BUT, the Pro Mini pinout I'm using shows the MISO and MOSI the other way around..... Just googled for other pin outs, and looks like it's a typo on my diagram! Very annoying. I'll throw that one away.
So please remove my remarks about the Pro Mini having different wiring sometimes.

**Comment by GIPdA** [comment]
Nice, mystery solved :-)

I just merged your commit, thanks. I changed a bit the name of the define, to be consistent with the lib, it's 'ZETARF_FREQUENCY_433MHZ' now ;-)

**Pull request merged**
